### ISSUE TITLE
Uint16List to float

### ISSUE THREAD

**Issue by tuceturan** [Hacker-CB/modbus-dart#20]
Hello how can convert to float data?

I try this Function

final bytes = Uint16List.fromList(data);
final byteData = ByteData.sublistView(bytes);
double value = byteData.getFloat32(0);
but this value is negative and swap value 
Can you help?

**Comment by hacker-cb** [comment]
There is no float type in mosbus.
You should use modbus registers accroding documentation to the the device you want to connect.

**Comment by tuceturan** [comment]
Okay I know but register data is float in device documentation

When I get [16134,54975] this array I want to change double first element
