### ISSUE TITLE
How about the rtu mode without tcp?

### ISSUE THREAD

**Issue by VesperHan** [Hacker-CB/modbus-dart#3]

**Comment by hacker-cb** [comment]
You mean RTU with Serial?
Serial is not implemented yet. Contributions are welcome

**Comment by doudouaixiaoyu** [comment]
请问接受和发送都能实现吗？

**Comment by hacker-cb** [comment]
MR welcome

**Comment by doudouaixiaoyu** [comment]
I saw your example,I do not see the sent code, I see 'var slaveIdResponse = await client.reportslaveid ();'Is the send performed here

**Comment by Exquemelin** [comment]
With this version of the code I only read data, but can I write data to a device?

**Comment by hacker-cb** [comment]
@Exquemelin yes, you can write. Something like ` client.writeMultipleRegisters()`, `client.writeSingleCoil()`, etc

**Comment by Exquemelin** [comment]
Ah, ok. Thank you for your fast support. I will try it.
